// Generated by scripts/generate.ts from process/instructions.ts. Do not edit; edit the source and run npm run generate.
/**
 * The process's public interface: each agent imports this from its
 * generated `process/instructions`.
 *
 * The lead gets one text on every turn: who it is, the platform's facts,
 * what it optimises for, its boundaries and the method it applies when the
 * work warrants it (design 019 §2 "The model drives; the method is a
 * skill"). A one-line preface names the turn; the render appends the turn's
 * data after it.
 */
import { BOUNDARIES } from "./boundaries";
import { FACTS } from "./facts";
import { implementerText } from "./implementer";
import { METHOD } from "./method";
import { reviewerText } from "./reviewer";
import { ROLES } from "./roles";
import { VALUES } from "./values";

export { TOOL_NAMES } from "./reports";

export type LeadInput = { source: "channel" | "event" | "subagent" };

const PREFACE: Record<LeadInput["source"], string> = {
  channel: "This turn: the person wrote in the thread.",
  event: "This turn: a builder's outcome arrived through your subscription; the person did not write. The parsed report follows the instructions.",
  subagent:
    "This turn: the reviewer answered your consult. The parsed answer and the messages the person wrote meanwhile follow the instructions.",
};

/** The lead's instruction text for one turn kind: the preface, then the same five parts on every turn. */
export function leadInstructions(input: LeadInput): string {
  return [PREFACE[input.source], ROLES.lead, FACTS, VALUES, BOUNDARIES, METHOD].join("\n\n");
}

/** The implementer's instruction text; the assignment arrives as the turn payload. */
export function implementerInstructions(): string {
  return implementerText();
}

/** The reviewer's instruction text; the brief arrives as the consult prompt. */
export function reviewerInstructions(): string {
  return reviewerText();
}
