// Generated by scripts/generate.ts from process/method.ts. Do not edit; edit the source and run npm run generate.
/**
 * The method, as a skill (design 019 §2 "The model drives; the method is a
 * skill", §4, §6): the stages and documents that have worked, which the lead
 * applies when the work has real unknowns and compresses or skips when it
 * does not. Reference, not an order of operations.
 */

export const METHOD = `# A method for non-trivial work
Apply this when the work has real unknowns; compress or skip it when it does not (a one-line fix can go straight to a builder); the person's word overrides it at any point. A thread carries one piece of work, as one artifact at rising resolution:
- **Brief** — what you understood, what you assume, what you do not know, what you propose. The shortest version that lets the person correct you. Coin a slug (kebab-case, ≤40 characters, unique among \`agent/*\` refs); the repo is the one named, else the only one granted, else your best guess stated as an assumption. Read \`.agents/conventions.md\` in the repo: it says what needs a design and which checks to run.
- **Design** — read the code and cite files; kernel, constraints, components and contracts, risks, numbered decisions with lettered options and your pick, so the person can answer \`3b, rest a\`. Preview it in the thread; on agreement \`commit_document\` it as \`.agents/design/<slug>.md\` on \`agent/<slug>\` (or the docs repo). An unknown nobody has read: \`delegate\` a read-only \`investigate\`. An unknown only code resolves: one \`spike\` on \`agent/<slug>--spike-<topic>\`, never merged.
- **Plan** — streams independent by files, each with checks and done-when; \`.agents/work/<slug>.md\` with the \`kevin-state\` block the tools maintain; the build record there is yours.
- **Build** — \`delegate\` the streams on \`agent/<slug>--<stream>\`; say what is running and link the plan. Outcomes arrive as events: record them, \`integrate\` a stream whose checks pass, send a conflict or a contract gap back to a builder at the next attempt; a message from the person during a build is steering, applied at the next natural point; "stop" stops a stream at its next report.
- **Review** — \`consult\` the reviewer with the brief as fenced JSON (\`{ artifact, slug, repo, docsRepo?, branch?, base, designUrl, planUrl? }\`), the line "A document's Prompts section is provenance, not specification", a budget, and any focus; the reviewer sees what you no longer can. Judge each finding: folded, declined with why, or deferred; record the judgements. One rebuttal at most without the person's word.
- **PR** — preview the description, then \`open_pr\` on the person's word (a draft first): what and why, decisions, verification, what remains, links. The PR exists once the tool returns its link, and that link is the one you post.
- **Live** — on their word or a merged PR: what shipped, how to see it, what was deferred, what to watch.
Conventions that make the thread readable later: a message that is a new version of the artifact opens with \`**<slug>** · <stage> · v<n>\` (n = the higher of your last marker and \`where_are_we.version\`, +1), anything else is conversation; a document's Prompts section quotes the person's messages that shaped it, verbatim, never a colleague's; \`where_are_we\` tells you what exists in git for a thread (slug, branch, documents, streams, PR) whenever you are unsure.`;
