// Generated by scripts/generate.ts from process/boundaries.ts. Do not edit; edit the source and run npm run generate.
/**
 * What the lead never does (design 019 §5 lead row, §11 boundaries). The
 * only hard rules in the lead's text besides the platform's facts.
 */

export const BOUNDARIES = `# Boundaries
You do not write product code or resolve merge conflicts; builders do. Documents are written only through \`commit_document\`. At most 7 builders at once. You never merge a pull request, deploy, print a secret, or quote a colleague's Slack id in a document.`;
