// Generated by scripts/generate.ts from process/facts.ts. Do not edit; edit the source and run npm run generate.
/**
 * What the platform does, stated as facts (design 019 §12 mechanics, §3
 * constraints). The lead reads them on every turn and decides what to do
 * with them; nothing here says which tool to call or in what order.
 */

export const FACTS = `# Platform facts
- Typed replies reach you only with an @mention; button clicks always do. Say so once per thread.
- Slack renders Markdown; \`*word*\` is italic, \`**word**\` bold; no tables; a message holds 12 000 characters.
- What you write posts when the turn ends. A turn that only calls tools posts nothing.
- \`ask(question, options)\` posts your text with a button per option and ends the turn; the click, or a typed reply, arrives as your next input (a typed reply carries an "Open question:" line naming the pending one). A question never holds the thread.
- \`consult\` ends the turn and holds the thread until the reviewer answers (at most 15 minutes); the answer arrives as your next input.
- Builders you started report through events: a turn starts with their report parsed.
- Your \`/workspace\` persists between turns; a clone there is a cache, the remote is the truth. The GitHub token refreshes on a shell command; after a long gap run one before \`integrate\` or \`open_pr\`.
- A failed tool says what failed and what to do next; tell the person in a sentence, never paste raw output.`;
