/**
 * Copies the one process source (`process/`) into each agent's `process/`.
 * The CLI bundler refuses imports outside an agent's directory,
 * so shared text is generated per agent and committed.
 *
 *   npm run generate            write
 *   npm run generate -- --check fail when any agent's copy differs
 */
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const SOURCE_DIR = "process";

export function header(file: string): string {
  return `// Generated by scripts/generate.ts from ${SOURCE_DIR}/${file}. Do not edit; edit the source and run npm run generate.\n`;
}

export interface Drift {
  agent: string;
  file: string;
  kind: "missing" | "stale" | "extra";
}

async function listFiles(dir: string): Promise<string[]> {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }
  const files: string[] = [];
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      for (const nested of await listFiles(path)) files.push(join(entry.name, nested));
    } else if (entry.isFile()) {
      files.push(entry.name);
    }
  }
  return files.sort();
}

async function readOptional(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

/** Compares (and, unless `check`, rewrites) every agent's process/ against the source. */
export async function generate(options: { root: string; agents: readonly string[]; check: boolean }): Promise<Drift[]> {
  const source = resolve(options.root, SOURCE_DIR);
  const files = (await listFiles(source)).filter((file) => file.endsWith(".ts"));
  const drift: Drift[] = [];
  for (const agent of options.agents) {
    const target = resolve(options.root, "opencomputer", "agents", agent, SOURCE_DIR);
    for (const file of files) {
      const expected = header(file) + (await readFile(join(source, file), "utf8"));
      const actual = await readOptional(join(target, file));
      if (actual === expected) continue;
      drift.push({ agent, file, kind: actual === undefined ? "missing" : "stale" });
      if (!options.check) {
        await mkdir(resolve(target, file, ".."), { recursive: true });
        await writeFile(join(target, file), expected);
      }
    }
    for (const file of await listFiles(target)) {
      if (files.includes(file)) continue;
      drift.push({ agent, file, kind: "extra" });
      if (!options.check) await rm(join(target, file));
    }
  }
  return drift;
}

async function main(): Promise<void> {
  const root = resolve(fileURLToPath(import.meta.url), "..", "..");
  const project = (await import(pathToFileURL(join(root, "opencomputer", "project.ts")).href)) as {
    default: { agents: readonly string[] };
  };
  const check = process.argv.includes("--check");
  const drift = await generate({ root, agents: project.default.agents, check });
  for (const item of drift) {
    const path = relative(root, join(root, "opencomputer", "agents", item.agent, SOURCE_DIR, item.file));
    console.log(`${check ? item.kind : `fixed ${item.kind}`}: ${path}`);
  }
  if (check && drift.length > 0) {
    console.error("process/ copies are out of date; run npm run generate");
    process.exitCode = 1;
  } else {
    console.log(`process/: ${project.default.agents.length} agents ${check ? "in sync" : "generated"}`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
